### ISSUE TITLE
Feature: button to jump back to the top

### ISSUE THREAD

**Issue by gruselhaus** [CodingTrain/project-trainsite#1]
Useful tool to "automatically scroll" back to the top https://github.com/tsuyoshiwada/sweet-scroll Example: https://tsuyoshiwada.github.io/sweet-scroll/

![47271807-2731bf00-d57d-11e8-86f7-e529bbc73db4](https://user-images.githubusercontent.com/33380107/49389999-fc17bf00-f727-11e8-9825-28f2031be843.jpg)

Originally posted by @gruselhaus in [#826](https://github.com/CodingTrain/website/issues/826), [#806](https://github.com/CodingTrain/website/issues/806)

**Comment by Fraasi** [comment]
This is quite trivial in plain js
```js
document.addEventListener('scroll', () => {
	if (window.scrollY > 1500) {
		// pop up the scroll back to top button element
	}
})

scrollBackToTopButtonElement.addEventListener('click', () => {
	window.scrollTo(0, 0)
})
```
Although named scrollTo, it doesn't actually scroll but jump (to x, y).    
That looks like a sweet 😄 library, but do we want to have a nice scrolling effect or just a 'jump back to top'?
