### ISSUE TITLE
It's about time

### ISSUE THREAD

**Issue by Fraasi** [CodingTrain/project-trainsite#3]
React & node person here. I would like to help and learn all of what is needed to build this kind of site from ground up. Jekyll and old existing site was too much to grasp when I was learning.  Hopefully I could contribute this time somehow.  
Should we start listing what to do/how to do in 'projects' tab or just make an todo.md for now, or what do people prefer?

**Comment by nilsweb** [comment]
Yes! Awesome! 🎉
A todo list or some form of roadmap would be great so we know, where to start. I'll probably create a project on GH for this to brainstorm ideas and later they can be grouped together as issues so we can start working on them.

**Comment by Fraasi** [comment]
Sounds like a plan, and a start:smile:

**Comment by nilsweb** [comment]
I finally got to it! Project can be found here: https://github.com/CodingTrain/project-trainsite/projects/1
